
```{r}
library(Seurat)
library(tximport)
library(ggplot2)
library(corrplot)
library(network)
#BiocManager::install("Rsamtools")
#install.packages("Signac")
library(Signac)
#remotes::install_github('satijalab/seurat-wrappers')
#install.packages("R.utils")
library(SeuratWrappers)
#install.packages("devtools")
#devtools::install_github('cole-trapnell-lab/leidenbase')
#BiocManager::install("limma")
#BiocManager::install("batchelor")
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
library(Matrix)
library(patchwork)
#devtools::install_version("uwot", version = "0.1.10", repos = "http://cran.us.r-project.org")
library(uwot)
set.seed(1234)
setwd("~/mydatalocal/scarabi/results")
```

```{r}

samps <- c("SRR8257100","SRR8257101","SRR8257102","SRR8257103","SRR8257104","SRR8257105","SRR8257106")
```

# path to the output directory of Alevin quant run 
```{r}
files <- file.path(
  paste("~/mydatalocal/scarabi/data/quant/",samps,"/alevin/quants_mat.gz", sep=""))
file.exists(files)

```

```{r}
txis <- lapply(files, function(f) tximport(files = f, type="alevin"))

```
```{r}

seu_objs <- lapply(seq_along(txis), function(i){
  # min.cells = 3, min.features = 200 from Ryu et al.
  s <- CreateSeuratObject(counts = txis[[i]]$counts , min.cells = 3, min.features = 200, project = samps[i]) 
  })
```


#Marie's edit here
```{r}
scarabWT <- merge(x = seu_objs[[1]], y = unlist(seu_objs[2:4], recursive = F), add.cell.ids = samps[1:4])

```

```{r}
scarabWT[["percent.mt"]] <- PercentageFeatureSet(scarabWT, pattern = "ATM")
scarabWT[["percent.chloro"]] <- PercentageFeatureSet(scarabWT, pattern = "ATC")
```

```{r}
quant <- quantile(scarabWT[["percent.mt"]]$percent.m,0.95 )
```
```{r}
scarabWT <-subset(scarabWT, subset =  percent.mt < quant & percent.chloro < 0.2)
```

```{r}
VlnPlot(scarabWT, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","percent.chloro"), ncol = 4)
```
```{r}

plot1 <- FeatureScatter(scarabWT, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(scarabWT, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
```

```{r}
scarabWT <- NormalizeData(scarabWT, normalization.method = "LogNormalize", scale.factor = 10000)
```
```{r}
scarabWT <- FindVariableFeatures(scarabWT, selection.method = "vst", nfeatures = 2000)
```

```{r}
all.genes <- rownames(scarabWT)
scarabWT <- ScaleData(scarabWT, features = all.genes)
```

```{r}
scarabWT <- RunPCA(scarabWT, features = VariableFeatures(object = scarabWT))
```

```{r}
VizDimLoadings(scarabWT, dims = 1:2, reduction = "pca")
```
```{r}
DimPlot(scarabWT, reduction = "pca")
```

```{r}
DimHeatmap(scarabWT, dims = 1:15, cells = 500, balanced = TRUE)
```

```{r}
DimHeatmap(scarabWT, dims = 1:15, cells = 200, balanced = TRUE)
```

```{r, eval = FALSE}
scarabWT <- JackStraw(scarabWT, num.replicate = 100)
scarabWT <- ScoreJackStraw(scarabWT, dims = 1:20)
```
```{r, eval = FALSE}
JackStrawPlot(scarabWT, dims = 1:15, xmax = 1, ymax = 1)
```
```{r}
ElbowPlot(scarabWT)
```

```{r}
scarabWT <- FindNeighbors(scarabWT, dims = 1:10)
scarabWT <- FindClusters(scarabWT, resolution = 0.8)
```

```{r}
scarabWT <- RunUMAP(scarabWT, dims = 1:5, return.model = TRUE)
```
```{r}
DimPlot(scarabWT, reduction = "umap")
```
```{r}
Markers = read.csv("../data/Markers.csv", sep = '\t', h=T)
Markers
```
```{r}
Table = table(Markers$Preferential.expression.in.root)
Table
```
```{r}
Markers$Locus<-gsub(" ","",Markers$Locus)
Markers$Preferential.expression.in.root<-gsub("/"," ",Markers$Preferential.expression.in.root)

lm<-split(Markers,Markers$Preferential.expression.in.root)


system("mkdir -p image")
system("rm -r image/*")

output <- lapply(names(lm),function(x){f<-FeaturePlot(scarabWT, features = lm[[x]]$Locus)
  ggsave(f,file=paste0("image/",x,".png"),width=40,height=40,units="cm")
  })

datascore <- data.frame(lapply(names(lm),function(x){score=colMeans(scarabWT@assays$RNA[lm[[x]]$Locus,])
  }))
names(datascore)<-make.names(names(lm))
scarabWT <- AddMetaData(scarabWT, metadata = datascore)
g<-FeaturePlot(scarabWT, features=names(datascore))
ggsave(g,file = "image/type_cellulaire.png",width=40,height=40,units="cm")

```
```{r}
samps<-read.table("~/mydatalocal/scarabi/data/Counts_Salmon/metadata_Li2016.txt", sep="\t")
#On trie les samples par types cellulaires
samps <- samps[order(samps$V3),]
#On supprime les types cellulaires non déterminants
samps <- samps[!samps$V3%in%c("whole root","whole root 1","cycloheximide treatment","cycloheximide mock"),]
samps
ech<-samps$V1
ech
```
```{r}
files <- file.path(
  paste("~/mydatalocal/scarabi/data/Counts_Salmon/",ech,"/quant.sf", sep=""))
files<-files[file.exists(files)]
files
```
```{r}
tx2gene<-read.table("~/mydatalocal/scarabi/processed_data/txp2gene.tsv")
names(tx2gene)<-c("TXNAME","GENEID")
tx2gene<-unique(tx2gene)
head(tx2gene)
```


```{r}
txis <- lapply(files, function(f) {
  tab<- tximport(files = f, type="salmon", tx2gene=tx2gene)
  return(tab$abundance)
  })
tabpur<-as.data.frame(txis)
```
```{r}
ech2=sapply(files,function(f){strsplit(f,"/")[[1]][6]})

#Changer le nom des colonnes du tableau 
names(tabpur)<-make.names(ech2)
head(tabpur)
```

```{r}
#Pour chaque cluster, on regarde l'expression moyenne des gènes dans le cluster
avg.e <- AverageExpression(scarabWT)
scarabWT_avg=data.frame(avg.e)

#On fait attention aux noms des gènes présents, car on n'a pas exactement les mêmes
genes_scarabi <- rownames(scarabWT_avg)
genes_li <- rownames(tabpur)
genes_common <- genes_scarabi[genes_scarabi%in%genes_li]

countsLi_norm_avg_alt_sum_c <- tabpur[genes_common,]
scarabWT_avg_c <- scarabWT_avg[genes_common,]

#Librairie nécessaire pour faire la corrélation
#install.packages("corrplot")
#install.packages("network")

#On calcule la matrice de corrélation entre les clusters et les samples
corLi_scarab_spearman <- cor(scarabWT_avg_c,countsLi_norm_avg_alt_sum_c,method="spearman")

#On change le nom des samples (aux colonnes) par le type cellulaire associé.
colnames(corLi_scarab_spearman) <- lapply(colnames(corLi_scarab_spearman), function(name){samps[samps$V1==name,3]})

corrplot(corLi_scarab_spearman, method="color", is.corr=F, tl.col = as.color(colnames(corLi_scarab_spearman)) )
```
```{r}
cluster.id <- max.col(corLi_scarab_spearman)
cluster.id  <- colnames(corLi_scarab_spearman)[cluster.id]
cluster.id 
```
```{r}
names(cluster.id) <- levels(scarabWT)
cluster.id
scarabWT <- RenameIdents(scarabWT, cluster.id)
DimPlot(scarabWT, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```

```{r}

samps <- c("SRR8257100","SRR8257101","SRR8257102","SRR8257103","SRR8257104","SRR8257105","SRR8257106")
```

# path to the output directory of Alevin quant run 
```{r}
files <- file.path(
  paste("~/mydatalocal/scarabi/data/quant/",samps,"/alevin/quants_mat.gz", sep=""))
file.exists(files)

```

```{r}
txi <- tximport(files = files[6], type="alevin")
```
```{r}
  scarabmut <- CreateSeuratObject(counts = txi$counts , min.cells = 3, min.features = 200, project = samps[6]) 
```


#Marie's edit here
```{r}
scarabmut[["percent.mt"]] <- PercentageFeatureSet(scarabmut, pattern = "ATM")
scarabmut[["percent.chloro"]] <- PercentageFeatureSet(scarabmut, pattern = "ATC")
```

```{r}
quant <- quantile(scarabmut[["percent.mt"]]$percent.m,0.95 )
```
```{r}
scarabmut <-subset(scarabmut, subset =  percent.mt < quant & percent.chloro < 0.2)
```

```{r}
VlnPlot(scarabmut, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","percent.chloro"), ncol = 4)
```
```{r}

plot1 <- FeatureScatter(scarabmut, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(scarabmut, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
```

```{r}
scarabmut <- NormalizeData(scarabmut, normalization.method = "LogNormalize", scale.factor = 10000)
```
```{r}
scarabmut <- FindVariableFeatures(scarabmut, selection.method = "vst", nfeatures = 2000)
```

```{r}
all.genes <- rownames(scarabmut)
scarabmut <- ScaleData(scarabmut, features = all.genes)
```

```{r}
scarabmut <- RunPCA(scarabmut, features = VariableFeatures(object = scarabmut))
```

```{r}
VizDimLoadings(scarabmut, dims = 1:2, reduction = "pca")
```
```{r}
DimPlot(scarabmut, reduction = "pca")
```

```{r}
DimHeatmap(scarabmut, dims = 1:15, cells = 500, balanced = TRUE)
```

```{r}
DimHeatmap(scarabmut, dims = 1:15, cells = 200, balanced = TRUE)
```

```{r, eval = FALSE}
scarabmut <- JackStraw(scarabmut, num.replicate = 100)
scarabmut <- ScoreJackStraw(scarabmut, dims = 1:20)
```
```{r, eval = FALSE}
JackStrawPlot(scarabmut, dims = 1:15, xmax = 1, ymax = 1)
```
```{r}
ElbowPlot(scarabmut)
```

```{r}
scarabmut <- FindNeighbors(scarabmut, dims = 1:10)
scarabmut <- FindClusters(scarabmut, resolution = 0.8)
```

```{r}
scarabmut <- RunUMAP(scarabmut, dims = 1:5, return.model = TRUE)
```
```{r}
DimPlot(scarabmut, reduction = "umap")
```
```{r}
Markers = read.csv("../data/Markers.csv", sep = '\t', h=T)
Markers
```
```{r}
Table = table(Markers$Preferential.expression.in.root)
Table
```

```{r}
samps<-read.table("~/mydatalocal/scarabi/data/Counts_Salmon/metadata_Li2016.txt", sep="\t")
#On trie les samples par types cellulaires
samps <- samps[order(samps$V3),]
#On supprime les types cellulaires non déterminants
samps <- samps[!samps$V3%in%c("whole root","whole root 1","cycloheximide treatment","cycloheximide mock"),]
samps
ech<-samps$V1
ech
```
```{r}
files <- file.path(
  paste("~/mydatalocal/scarabi/data/Counts_Salmon/",ech,"/quant.sf", sep=""))
files<-files[file.exists(files)]
files
```
```{r}
tx2gene<-read.table("~/mydatalocal/scarabi/processed_data/txp2gene.tsv")
names(tx2gene)<-c("TXNAME","GENEID")
tx2gene<-unique(tx2gene)
head(tx2gene)
```


```{r}
txis <- lapply(files, function(f) {
  tab<- tximport(files = f, type="salmon", tx2gene=tx2gene)
  return(tab$abundance)
  })
tabpur<-as.data.frame(txis)
```
```{r}
ech2=sapply(files,function(f){strsplit(f,"/")[[1]][6]})

#Changer le nom des colonnes du tableau 
names(tabpur)<-make.names(ech2)
head(tabpur)
```

```{r}
#Pour chaque cluster, on regarde l'expression moyenne des gènes dans le cluster
avg.e <- AverageExpression(scarabmut)
scarabmut_avg=data.frame(avg.e)

#On fait attention aux noms des gènes présents, car on n'a pas exactement les mêmes
genes_scarabi <- rownames(scarabmut_avg)
genes_li <- rownames(tabpur)
genes_common <- genes_scarabi[genes_scarabi%in%genes_li]

countsLi_norm_avg_alt_sum_c <- tabpur[genes_common,]
scarabmut_avg_c <- scarabmut_avg[genes_common,]

#Librairie nécessaire pour faire la corrélation
#install.packages("corrplot")
#install.packages("network")

#On calcule la matrice de corrélation entre les clusters et les samples
corLi_scarab_spearman <- cor(scarabmut_avg_c,countsLi_norm_avg_alt_sum_c,method="spearman")

#On change le nom des samples (aux colonnes) par le type cellulaire associé.
colnames(corLi_scarab_spearman) <- lapply(colnames(corLi_scarab_spearman), function(name){samps[samps$V1==name,3]})

corrplot(corLi_scarab_spearman, method="color", is.corr=F, tl.col = as.color(colnames(corLi_scarab_spearman)) )
```
```{r}
cluster.id <- max.col(corLi_scarab_spearman)
cluster.id  <- colnames(corLi_scarab_spearman)[cluster.id]
cluster.id 
```
```{r}
names(cluster.id) <- levels(scarabmut)
cluster.id
scarabmut <- RenameIdents(scarabmut, cluster.id)
DimPlot(scarabmut, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```

```{r}
scarab.anchors <- FindTransferAnchors(reference = scarabWT, query = scarabmut,
                                      dims = 1:30, reference.reduction = "pca")

scarabmut <- MapQuery(anchorset = scarab.anchors, reference = scarabWT, query = scarabmut,
                       reference.reduction = "pca", reduction.model = "umap")

pbmc.atac.filtered$predicted.id <- factor(pbmc.atac.filtered$predicted.id, levels = levels(pbmc.rna))  # to make the colors match
  
p1 <- DimPlot(scarabWT, reduction = "umap", group.by = "seurat_clusters", label = TRUE, label.size = 3,
              repel = TRUE) + NoLegend() + ggtitle("Reference annotations")
p2 <- DimPlot(scarabmut, reduction = "ref.umap", group.by = "predicted.id", label = TRUE,
              label.size = 3, repel = TRUE, split.by = "orig.ident") + NoLegend() + ggtitle("Query transferred labels")
p1 + p2
```

```{r}
scarabWT[["UMAP"]] <- scarabWT[["umap"]]
# To save on memory, you can delete the original UMAP, but this is not necessary
scarabWT[["umap"]] <- NULL

scarabWT.cds <- as.cell_data_set(scarabWT)
scarabWT.cds <- cluster_cells(cds = scarabWT.cds, reduction_method = "UMAP")
scarabWT.cds <- learn_graph(scarabWT.cds, use_partition = TRUE)
```
```{r}
 hsc <- c("SRR8257100_CCACTACCAAGTTGTC","SRR8257100_CGAATGTTCAGGTAAA")
scarabWT.cds <- order_cells(scarabWT.cds, reduction_method = "UMAP", root_cells = hsc)
plot_cells(
  cds = scarabWT.cds,
  color_cells_by = "pseudotime",
  show_trajectory_graph = TRUE
)
```

